name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set up Husky hooks
        run: |
          npx husky-init
          npx husky install
          npx husky add .husky/commit-msg 'npx --no-install commitlint --edit "%1"'

      - name: Run Semantic Release
        run: npx run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM-TOKEN }}
